### ISSUE TITLE
ClangBear throws exception

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala-bears#329]
```
[DEBUG][22:35:42] The bear ClangBear raised an exception. If you are the writer of this bear, please make sure to catch all exceptions. If not and this error annoys you, you might want to get in contact with the writer of this bear.

Traceback information is provided below:

Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/coalib/bears/Bear.py", line 97, in execute
    return list(self.run_bear_from_section(args, kwargs) or [])
  File "/home/lasse/prog/coala-bears/bears/c_languages/ClangBear.py", line 46, in run
    for range in diag.ranges)
  File "/home/lasse/prog/coala-bears/bears/c_languages/ClangBear.py", line 46, in <genexpr>
    for range in diag.ranges)
  File "/usr/lib/python3.5/site-packages/coalib/results/SourceRange.py", line 54, in from_clang_range
    return cls.from_values(range.start.file.name,
AttributeError: 'NoneType' object has no attribute 'name'
```

type/bug difficulty/low I guess

**Comment by Uran198** [comment]
How to reproduce, or it throws it on every run?

**Comment by sils1297** [comment]
I think I was running ClangBear on https://github.com/mapsme/omim
