### ISSUE TITLE
Can't run ESLintBear

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala-bears#411]
```
[DEBUG][13:26:03] The bear ESLintBear raised an exception. If you are the writer of this bear, please make sure to catch all exceptions. If not and this error annoys you, you might want to get in contact with the writer of this bear.

Traceback information is provided below:

Traceback (most recent call last):
  File "/home/lasse/venvs/def/lib/python3.5/site-packages/coalib/bears/Bear.py", line 116, in execute
    return list(self.run_bear_from_section(args, kwargs) or [])
  File "/home/lasse/prog/coala-bears/bears/js/ESLintBear.py", line 36, in process_output
    output = json.loads(output)
  File "/usr/lib64/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by sils1297** [comment]
Having an old version, updating helps.
