### ISSUE TITLE
PerlCriticBear: Don't use shutil.which

### ISSUE THREAD

**Issue by Makman2** [coala-analyzer/coala-bears#497]
You receive errors when trying to import the bear because passing `None` as an executable to linter is forbidden.

**Comment by Makman2** [comment]
mak@hp-elitebook:~$ coala -l Perl -L=DEBUG
[WARNING][16:19:37] The default coafile '.coafile' was not found. You can generate a configuration file with your current options by adding the `--save` flag.
[WARNING][16:19:37] coala will not run any analysis. Did you forget to give the `--files` argument?
[WARNING][16:19:37] coala will not run any analysis. Did you forget to give the `--bears` argument?
[WARNING][16:19:37] Unable to collect bears from /usr/lib/python3.4/site-packages/bears/perl/PerlCriticBear.py. Probably the file is malformed or the module code raises an exception.
[DEBUG][16:19:37] Exception was:
Traceback (most recent call last):

  File "/usr/lib/python3.4/site-packages/coalib/collecting/Collectors.py", line 124, in icollect_bears
    for bear in _import_bears(matching_file, kinds):

  File "/usr/lib/python3.4/site-packages/coalib/collecting/Collectors.py", line 26, in _import_bears
    types=list):

  File "/usr/lib/python3.4/site-packages/coalib/collecting/Importers.py", line 151, in iimport_objects
    attributes, local):

  File "/usr/lib/python3.4/site-packages/coala_decorators/decorators.py", line 14, in yield_once_generator
    for item in iterator(*args, **kwargs):

  File "/usr/lib/python3.4/site-packages/coalib/collecting/Importers.py", line 122, in _iimport_objects
    module = _import_module(file_path)

  File "/usr/lib/python3.4/site-packages/coalib/collecting/Importers.py", line 30, in _import_module
    return __import__(module_name)

  File "/usr/lib/python3.4/site-packages/bears/perl/PerlCriticBear.py", line 18, in <module>
    "5": RESULT_SEVERITY.INFO})

  File "/usr/lib/python3.4/site-packages/coala_decorators/decorators.py", line 296, in decorated
    assert_right_type(argval, annotations[argname], argname)

  File "/usr/lib/python3.4/site-packages/coala_decorators/decorators.py", line 257, in assert_right_type
    "{})".format(argname, types, repr(value)))

TypeError: executable must be an instance of one of (<class 'str'>,) (provided value: None)
[WARNING][16:19:38] Unable to collect bears from /usr/lib/python3.4/site-packages/bears/perl/PerlCriticBear.py. Probably the file is malformed or the module code raises an exception.
[DEBUG][16:19:38] Exception was:
Traceback (most recent call last):

  File "/usr/lib/python3.4/site-packages/coalib/collecting/Collectors.py", line 124, in icollect_bears
    for bear in _import_bears(matching_file, kinds):

  File "/usr/lib/python3.4/site-packages/coalib/collecting/Collectors.py", line 26, in _import_bears
    types=list):

  File "/usr/lib/python3.4/site-packages/coalib/collecting/Importers.py", line 151, in iimport_objects
    attributes, local):

  File "/usr/lib/python3.4/site-packages/coala_decorators/decorators.py", line 14, in yield_once_generator
    for item in iterator(*args, **kwargs):

  File "/usr/lib/python3.4/site-packages/coalib/collecting/Importers.py", line 122, in _iimport_objects
    module = _import_module(file_path)

  File "/usr/lib/python3.4/site-packages/coalib/collecting/Importers.py", line 30, in _import_module
    return __import__(module_name)

  File "/usr/lib/python3.4/site-packages/bears/perl/PerlCriticBear.py", line 18, in <module>
    "5": RESULT_SEVERITY.INFO})

  File "/usr/lib/python3.4/site-packages/coala_decorators/decorators.py", line 296, in decorated
    assert_right_type(argval, annotations[argname], argname)

  File "/usr/lib/python3.4/site-packages/coala_decorators/decorators.py", line 257, in assert_right_type
    "{})".format(argname, types, repr(value)))

TypeError: executable must be an instance of one of (<class 'str'>,) (provided value: None)
FilenameBear

**Comment by Makman2** [comment]
This was solved with 64795ac0c87171f98acd19f52574178ce613570a
