### ISSUE TITLE
ESLintBear doesn't work

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala-bears#572]
```
[WARNING][21:48:43] Bear ESLintBear failed to run. Take a look at debug messages (`-L DEBUG`) for further information.
[DEBUG][21:48:43] The bear ESLintBear raised an exception. If you are the writer of this bear, please make sure to catch all exceptions. If not and this error annoys you, you might want to get in contact with the writer of this bear.

Traceback information is provided below:

Traceback (most recent call last):
  File "/home/lasse/venvs/def/lib/python3.5/site-packages/coalib/bears/Bear.py", line 232, in execute
    return list(self.run_bear_from_section(args, kwargs) or [])
  File "/home/lasse/venvs/def/lib/python3.5/site-packages/bears/js/ESLintBear.py", line 43, in process_output
    output = json.loads(output)
  File "/usr/lib64/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by sils1297** [comment]
@hypothesist btw. this is release critical

**Comment by RaitoBezarius** [comment]
@sils1297 Now, closed?

**Comment by sils1297** [comment]
Right
