### ISSUE TITLE
Pip install fail with java on mac 

### ISSUE THREAD

**Issue by IgnatiousFlo** [coala-analyzer/coala-bears#621]
In a fresh virtual environment with python 3.5.2 on a Mac. 

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/rx/6bg2t2rx0hj6pdms2pw5lykm0000gn/T/pip-build-cwo5pyjz/language-check/setup.py", line 597, in <module>
        sys.exit(main())
      File "/private/var/folders/rx/6bg2t2rx0hj6pdms2pw5lykm0000gn/T/pip-build-cwo5pyjz/language-check/setup.py", line 592, in main
        run_setup_hooks(config)
      File "/private/var/folders/rx/6bg2t2rx0hj6pdms2pw5lykm0000gn/T/pip-build-cwo5pyjz/language-check/setup.py", line 561, in run_setup_hooks
        language_tool_hook(config)
      File "/private/var/folders/rx/6bg2t2rx0hj6pdms2pw5lykm0000gn/T/pip-build-cwo5pyjz/language-check/setup.py", line 586, in language_tool_hook
        download_lt()
      File "/private/var/folders/rx/6bg2t2rx0hj6pdms2pw5lykm0000gn/T/pip-build-cwo5pyjz/language-check/download_lt.py", line 117, in download_lt
        version = get_newest_possible_languagetool_version()
      File "/private/var/folders/rx/6bg2t2rx0hj6pdms2pw5lykm0000gn/T/pip-build-cwo5pyjz/language-check/download_lt.py", line 81, in get_newest_possible_languagetool_version
        universal_newlines=True)
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py", line 626, in check_output
        **kwargs).stdout
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py", line 708, in run
        output=stdout, stderr=stderr)
    subprocess.CalledProcessError: Command '['/usr/bin/java', '-version']' returned non-zero exit status 1

Running Java -version returns

No Java runtime present, requesting install.

**Comment by sils1297** [comment]
CC @Udayan12167 @AbdealiJK ideally if one of the bear dependencies fails to install, this one in particular, we'd just continue installation without it. Question is, can pip do that somehow?

**Comment by sils1297** [comment]
Also CC @Adrianzatreanu because his project would solve this as well.

**Comment by IgnatiousFlo** [comment]
I installed Java for the Mac from this url and it now runs fine. 

https://support.apple.com/kb/DL1572?locale=en_US

**Comment by AbdealiJK** [comment]
Pip has no way to handle a optional dependency.
I think it would be worthwhile to make a PR in language-check which gives a better error message in case java is not installed, as it's a dependency for language-check.

**Comment by Makman2** [comment]
agreeing with @AbdealiJK

**Comment by AbdealiJK** [comment]
Closing this, We now have `cib` which can install a single bear and this is unnecessary
