### ISSUE TITLE
YapfBear: Catch errors and make a result

### ISSUE THREAD

**Issue by underyx** [coala-analyzer/coala-bears#750]
When trying this test case: `self.check_validity(self.uut, ['async def x():\n', '0\n'], valid=True)`

I got a traceback:
```
Bear YapfBear failed to run. Take a look at debug messages (`-L DEBUG`) for further information.
The bear YapfBear raised an exception. If you are the writer of this bear, please make sure to catch all exceptions. If not and this error annoys you, you might want to get in contact with the writer of this bear.

Traceback information is provided below:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/yapf/yapflib/pytree_utils.py", line 101, in ParseCodeToTree
    tree = parser_driver.parse_string(code, debug=False)
  File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/lib2to3/pgen2/driver.py", line 106, in parse_string
    return self.parse_tokens(tokens, debug)
  File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/lib2to3/pgen2/driver.py", line 71, in parse_tokens
    if p.addtoken(type, value, (prefix, start)):
  File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/lib2to3/pgen2/parse.py", line 159, in addtoken
    raise ParseError("bad input", type, value, context)
lib2to3.pgen2.parse.ParseError: bad input: type=2, value='0', context=('', (2, 0))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/yapf/yapflib/pytree_utils.py", line 107, in ParseCodeToTree
    tree = parser_driver.parse_string(code, debug=False)
  File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/lib2to3/pgen2/driver.py", line 106, in parse_string
    return self.parse_tokens(tokens, debug)
  File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/lib2to3/pgen2/driver.py", line 71, in parse_tokens
    if p.addtoken(type, value, (prefix, start)):
  File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/lib2to3/pgen2/parse.py", line 159, in addtoken
    raise ParseError("bad input", type, value, context)
lib2to3.pgen2.parse.ParseError: bad input: type=2, value='0', context=('', (2, 0))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/coalib/bears/Bear.py", line 250, in execute
    return [] if result is None else list(result)
  File "/Users/underyx/coala-bears/bears/python/YapfBear.py", line 146, in run
    verify=False)[0].splitlines(True)
  File "/usr/local/lib/python3.5/site-packages/yapf/yapflib/yapf_api.py", line 90, in FormatFile
    verify=verify)
  File "/usr/local/lib/python3.5/site-packages/yapf/yapflib/yapf_api.py", line 123, in FormatCode
    tree = pytree_utils.ParseCodeToTree(unformatted_source)
  File "/usr/local/lib/python3.5/site-packages/yapf/yapflib/pytree_utils.py", line 113, in ParseCodeToTree
    raise e
  File "/usr/local/lib/python3.5/site-packages/yapf/yapflib/pytree_utils.py", line 111, in ParseCodeToTree
    ast.parse(code)
  File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 2
    0
    ^
IndentationError: expected an indented block
```

**Comment by underyx** [comment]
@sils1297 you sillyhead this is just the verbose logging :D close?

**Comment by AbdealiJK** [comment]
Are you sure this is with debug on ?
It says `Take a look at debug messages (`-L DEBUG`) for further information.` on top => it is not already in -L DEBUG

**Comment by underyx** [comment]
I'm not sure what happened behind the scenes — I just ran `pytest`.

**Comment by sils1297** [comment]
our test execution functions automatically capture the debug logs for you :)

**Comment by sils1297** [comment]
the `-L DEBUG` hint gets shown even if it's already active
